### ISSUE TITLE
麻烦你把数据集也上传一下呗，谢谢！或者给一下数据集链接

### ISSUE THREAD

**Issue by cookie918** [yangheng11/vertbi_cutWords#1]

**Comment by cookie918** [comment]
http://www.sogou.com/labs/resource/w.php

**Comment by yangheng11** [comment]
数据是csdn上的，我一已readme 添加链接



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael"; 
发送时间: 2019年11月11日(星期一) 中午1:45
收件人: "yangheng11/vertbi_cutWords";
抄送: "Subscribed";
主题: Re: [yangheng11/vertbi_cutWords] 麻烦你把数据集也上传一下呗，谢谢！或者给一下数据集链接 (#1)




Closed #1.
 
&mdash;

**Comment by yangheng11** [comment]
连接已经给了在readme里面



---原始邮件---
发件人: "Michael"<notifications@github.com&gt;
发送时间: 2019年11月11日(星期一) 中午1:45
收件人: "yangheng11/vertbi_cutWords"<vertbi_cutWords@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [yangheng11/vertbi_cutWords] 麻烦你把数据集也上传一下呗，谢谢！或者给一下数据集链接 (#1)



Closed #1.

**Comment by cookie918** [comment]
thanks




| |
Michael
邮箱：qiangyongjun918@163.com
|

Signature is customized by Netease Mail Master

在2019年11月20日 10:23，yangheng11 写道：
连接已经给了在readme里面



---原始邮件---
发件人: "Michael"<notifications@github.com&gt;
发送时间: 2019年11月11日(星期一) 中午1:45
收件人: "yangheng11/vertbi_cutWords"<vertbi_cutWords@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [yangheng11/vertbi_cutWords] 麻烦你把数据集也上传一下呗，谢谢！或者给一下数据集链接 (#1)



Closed #1.
